const config=window.DAMGA_CONFIG||{};let customerPhone=null,currentStamps=0;const $=id=>document.getElementById(id);
function showMessage(el,text,type=""){el.textContent=text;el.className="message "+type}
function normalizePhone(v){let p=v.replace(/\D/g,"");if(p.startsWith("90")&&p.length===12)p="0"+p.substring(2);if(p.length===10&&p.startsWith("5"))p="0"+p;return p}
function validPhone(p){return /^05\d{9}$/.test(p)}
function renderStamps(count){const e=$("stamps");e.innerHTML="";for(let i=1;i<=10;i++){const d=document.createElement("div");d.className="stamp"+(i<=count?" filled":"");d.textContent=i<=count?"✓":i;e.appendChild(d)}$("count").textContent=`${count} / 10 Damga`}
async function apiRequest(endpoint,data){const r=await fetch(`${config.SUPABASE_URL}/functions/v1/${endpoint}`,{method:"POST",headers:{"Content-Type":"application/json","apikey":config.SUPABASE_ANON_KEY,"Authorization":`Bearer ${config.SUPABASE_ANON_KEY}`},body:JSON.stringify(data)});const result=await r.json().catch(()=>({}));if(!r.ok)throw new Error(result.error||"İşlem başarısız.");return result}
$("phoneForm").addEventListener("submit",async e=>{e.preventDefault();const phone=normalizePhone($("phone").value);showMessage($("message"),"");if(!validPhone(phone)){showMessage($("message"),"Geçerli bir telefon numarası girin.","error");return}try{const data=await apiRequest("customer",{phone});customerPhone=phone;currentStamps=Number(data.stamps||0);$("customerCard").classList.remove("hidden");$("customerPhone").textContent=phone;renderStamps(currentStamps);$("pinBox").classList.add("hidden");showMessage($("result"),data.exists?"Kartınız açıldı.":"Yeni kartınız oluşturuldu.","success")}catch(error){showMessage($("message"),error.message,"error")}});
$("stampButton").addEventListener("click",()=>{$("pinBox").classList.remove("hidden");$("pin").value="";$("pin").focus()});
$("cancelButton").addEventListener("click",()=>$("pinBox").classList.add("hidden"));
$("confirmButton").addEventListener("click",async()=>{const pin=$("pin").value.trim();if(!/^\d{4}$/.test(pin)){showMessage($("result"),"4 haneli şifreyi girin.","error");return}$("confirmButton").disabled=true;try{const data=await apiRequest("stamp",{phone:customerPhone,pin});currentStamps=Number(data.stamps);renderStamps(currentStamps);$("pinBox").classList.add("hidden");showMessage($("result"),currentStamps>=10?"Tebrikler! 10 damgaya ulaştınız.":"Damganız başarıyla eklendi.","success")}catch(error){showMessage($("result"),error.message,"error")}finally{$("confirmButton").disabled=false}});